// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the discriminators for accounts and events defined in the IDL.

package perpetuals

// Account discriminators
var (
	Account_Custody         = [8]byte{1, 184, 48, 81, 93, 131, 63, 145}
	Account_Perpetuals      = [8]byte{28, 167, 98, 191, 104, 82, 108, 196}
	Account_Pool            = [8]byte{241, 154, 109, 4, 17, 177, 109, 188}
	Account_PositionRequest = [8]byte{12, 38, 250, 199, 46, 154, 32, 216}
	Account_Position        = [8]byte{170, 188, 143, 228, 122, 64, 247, 208}
	Account_TokenLedger     = [8]byte{156, 247, 9, 188, 54, 108, 85, 77}
)

// Event discriminators
var (
	Event_CreatePositionRequestEvent    = [8]byte{2, 238, 94, 53, 105, 211, 46, 186}
	Event_InstantCreateTpslEvent        = [8]byte{242, 54, 6, 95, 24, 141, 103, 198}
	Event_InstantUpdateTpslEvent        = [8]byte{177, 22, 47, 37, 120, 246, 17, 101}
	Event_ClosePositionRequestEvent     = [8]byte{21, 34, 92, 158, 224, 29, 180, 243}
	Event_IncreasePositionEvent         = [8]byte{245, 113, 85, 52, 214, 187, 153, 132}
	Event_IncreasePositionPreSwapEvent  = [8]byte{237, 107, 9, 139, 22, 75, 4, 213}
	Event_DecreasePositionEvent         = [8]byte{64, 156, 43, 74, 109, 131, 16, 127}
	Event_DecreasePositionPostSwapEvent = [8]byte{23, 210, 16, 233, 98, 245, 89, 82}
	Event_LiquidateFullPositionEvent    = [8]byte{128, 101, 71, 168, 128, 72, 86, 84}
	Event_PoolSwapEvent                 = [8]byte{40, 107, 212, 26, 223, 136, 39, 220}
	Event_PoolSwapExactOutEvent         = [8]byte{121, 118, 11, 11, 198, 66, 142, 115}
	Event_AddLiquidityEvent             = [8]byte{27, 178, 153, 186, 47, 196, 140, 45}
	Event_RemoveLiquidityEvent          = [8]byte{141, 199, 182, 123, 159, 94, 215, 102}
	Event_InstantCreateLimitOrderEvent  = [8]byte{10, 163, 85, 115, 129, 224, 80, 192}
	Event_InstantIncreasePositionEvent  = [8]byte{205, 236, 57, 4, 209, 106, 87, 69}
	Event_InstantDecreasePositionEvent  = [8]byte{171, 173, 106, 25, 239, 190, 58, 59}
)

// Instruction discriminators
var (
	Instruction_Init                                = [8]byte{220, 59, 207, 236, 108, 250, 47, 100}
	Instruction_AddPool                             = [8]byte{115, 230, 212, 211, 175, 49, 39, 169}
	Instruction_AddCustody                          = [8]byte{247, 254, 126, 17, 26, 6, 215, 117}
	Instruction_SetCustodyConfig                    = [8]byte{133, 97, 130, 143, 215, 229, 36, 176}
	Instruction_SetPoolConfig                       = [8]byte{216, 87, 65, 125, 113, 110, 185, 120}
	Instruction_SetPerpetualsConfig                 = [8]byte{80, 72, 21, 191, 29, 121, 45, 111}
	Instruction_TransferAdmin                       = [8]byte{42, 242, 66, 106, 228, 10, 111, 156}
	Instruction_WithdrawFees2                       = [8]byte{252, 128, 143, 145, 225, 221, 159, 207}
	Instruction_CreateTokenMetadata                 = [8]byte{221, 80, 176, 37, 153, 188, 160, 68}
	Instruction_CreateTokenLedger                   = [8]byte{232, 242, 197, 253, 240, 143, 129, 52}
	Instruction_ReallocCustody                      = [8]byte{123, 58, 109, 139, 133, 7, 225, 200}
	Instruction_ReallocPool                         = [8]byte{114, 128, 37, 167, 71, 227, 40, 178}
	Instruction_OperatorSetCustodyConfig            = [8]byte{166, 137, 92, 204, 145, 224, 24, 218}
	Instruction_OperatorSetPoolConfig               = [8]byte{76, 201, 80, 18, 199, 92, 246, 105}
	Instruction_TestInit                            = [8]byte{48, 51, 92, 122, 81, 19, 112, 41}
	Instruction_SetTestTime                         = [8]byte{242, 231, 177, 251, 126, 145, 159, 104}
	Instruction_SetTokenLedger                      = [8]byte{228, 85, 185, 112, 78, 79, 77, 2}
	Instruction_Swap2                               = [8]byte{65, 75, 63, 76, 235, 91, 91, 136}
	Instruction_AddLiquidity2                       = [8]byte{228, 162, 78, 28, 70, 219, 116, 115}
	Instruction_RemoveLiquidity2                    = [8]byte{230, 215, 82, 127, 241, 101, 227, 146}
	Instruction_CreateIncreasePositionMarketRequest = [8]byte{184, 85, 199, 24, 105, 171, 156, 56}
	Instruction_CreateDecreasePositionRequest2      = [8]byte{105, 64, 201, 82, 250, 14, 109, 77}
	Instruction_CreateDecreasePositionMarketRequest = [8]byte{74, 198, 195, 86, 193, 99, 1, 79}
	Instruction_UpdateDecreasePositionRequest2      = [8]byte{144, 200, 249, 255, 108, 217, 249, 116}
	Instruction_ClosePositionRequest                = [8]byte{40, 105, 217, 188, 220, 45, 109, 110}
	Instruction_ClosePositionRequest2               = [8]byte{121, 68, 162, 28, 216, 47, 200, 66}
	Instruction_IncreasePosition4                   = [8]byte{67, 147, 53, 23, 43, 57, 16, 67}
	Instruction_IncreasePositionPreSwap             = [8]byte{26, 136, 225, 217, 22, 21, 83, 20}
	Instruction_IncreasePositionWithInternalSwap    = [8]byte{114, 55, 106, 140, 199, 221, 32, 112}
	Instruction_DecreasePosition4                   = [8]byte{185, 161, 114, 175, 96, 148, 3, 170}
	Instruction_DecreasePositionWithInternalSwap    = [8]byte{131, 17, 153, 110, 119, 100, 97, 38}
	Instruction_LiquidateFullPosition4              = [8]byte{64, 176, 88, 51, 168, 188, 156, 175}
	Instruction_RefreshAssetsUnderManagement        = [8]byte{162, 0, 215, 55, 225, 15, 185, 0}
	Instruction_InstantCreateTpsl                   = [8]byte{117, 98, 66, 127, 30, 50, 73, 185}
	Instruction_InstantCreateLimitOrder             = [8]byte{194, 37, 195, 123, 40, 127, 126, 156}
	Instruction_InstantIncreasePosition             = [8]byte{164, 126, 68, 182, 223, 166, 64, 183}
	Instruction_InstantDecreasePosition             = [8]byte{46, 23, 240, 44, 30, 138, 94, 140}
	Instruction_InstantUpdateLimitOrder             = [8]byte{136, 245, 229, 58, 121, 141, 12, 207}
	Instruction_InstantUpdateTpsl                   = [8]byte{144, 228, 114, 37, 165, 242, 111, 101}
	Instruction_GetAddLiquidityAmountAndFee2        = [8]byte{109, 157, 55, 169, 8, 81, 4, 118}
	Instruction_GetRemoveLiquidityAmountAndFee2     = [8]byte{183, 59, 72, 110, 223, 243, 150, 142}
	Instruction_GetAssetsUnderManagement2           = [8]byte{193, 210, 13, 249, 113, 149, 29, 84}
)
